sorin_shop_list:
    path:     /
    defaults: { _controller: SorinShopBundle:Shop:list }

sorin_shop_get:
    path:      /get/{id}
    defaults:  { _controller: SorinShopBundle:Shop:get }


sorin_shop_create:
    path:      /create
    defaults:  { _controller: SorinShopBundle:Shop:create }

sorin_shop_set:
    path:      /set
    defaults:  { _controller: SorinShopBundle:Shop:set }

